# 语言配置字典
TRANSLATIONS = {
    "en": {
        "welcome": "Welcome to Password Manager!",
        "menu": """
1. Add new password
2. Get password
3. List all accounts
4. Delete password
5. Export passwords
6. Import passwords
7. Change language
8. Exit
""",
        "select_option": "Please select an option: ",
        "enter_account": "Enter account name: ",
        "enter_password": "Enter password (press Enter to generate one): ",
        "account_exists": "Account already exists!",
        "password_saved": "Password saved successfully!",
        "account_not_found": "Account not found!",
        "password_for": "Password for {}: {}",
        "no_passwords": "No passwords stored.",
        "accounts_list": "Stored accounts:",
        "delete_success": "Password deleted successfully!",
        "select_language": "Select language (en/zh): ",
        "invalid_option": "Invalid option, please try again.",
        "goodbye": "Goodbye!",
        "enter_password_length": "Enter password length: ",
        "enter_exclude_chars": "Enter characters to exclude (optional): ",
        "enter_note": "Enter note (optional): ",
        "enter_search_keyword": "Enter search keyword (optional): ",
        "enter_password_id": "Enter password ID: ",
        "enter_export_path": "Enter export file path: ",
        "enter_import_path": "Enter import file path: ",
        "language_changed": "Language changed successfully!",
        "press_enter": "Press Enter to continue...",
        "generated_password": "Generated password: ",
        "generation_time": "Generation time: {} seconds",
        "satisfied_password": "Are you satisfied with this password?",
        "modify_parameters": "Do you want to modify generation parameters?",
        "enter_new_length": "Enter new password length: ",
        "regenerating": "Regenerating password...",
        "no_permission_dir": "No permission to create directory: {}",
        "no_permission_file": "No permission to write file: {}",
        "invalid_path": "Invalid file path: {}",
        "help_password_length": "Password length",
        "help_exclude_chars": "Characters to exclude",
        "help_account_name": "Account name",
        "help_note": "Note information",
        "help_search": "Search keyword",
        "help_password_id": "Password ID to delete",
        "help_export_path": "Path to export file",
        "help_import_path": "Path to import file",
        "seconds": "seconds",
        "back_to_menu": "Back to main menu",
        "back_option": "Enter 'b' to go back to main menu",
        "going_back": "Going back to main menu...",
        "found_records": "Found {} records",
        "no_records_found": "No records found",
        "record_details": "Record details",
        "warning_delete_all": "Warning: About to delete all {} password records!",
        "existing_records": "Existing records",
        "operation_irreversible": "This operation is irreversible!",
        "confirm_clear_all": "Are you sure to clear all records?",
        "confirm_clear_all_again": "Confirm again to clear all records?",
        "clear_cancelled": "Clear operation cancelled",
        "no_records_in_db": "No records in database",
        "confirm_delete": "Confirm to delete this record?",
        "delete_cancelled": "Delete operation cancelled",
        "file_not_exists": "File does not exist: {}",
        "export_success": "Successfully exported passwords to: {}",
        "export_failed": "Export failed: {}",
        "import_success": "Successfully imported passwords from: {}",
        "import_failed": "Import failed: {}",
        "clear_success": "Successfully cleared all records",
        "clear_failed": "Clear operation failed",
        "delete_success": "Successfully deleted record",
        "delete_failed": "Delete operation failed",
        "available_accounts": "Available accounts for deletion:",
        "account_id_format": "ID: {}, Account: {}",
        "search_before_delete": "Search accounts before deletion (optional): ",
        "more_records": "... and {} more records (use search to filter)",
        "delete_options": """Choose operation:
1. Delete by ID
2. Search and delete""",
        "select_delete_option": "Enter your choice: ",
    },
    "zh": {
        "welcome": "欢迎使用密码管理器！",
        "menu": """
1. 添加新密码
2. 获取密码
3. 列出所有账户
4. 删除密码
5. 导出密码
6. 导入密码
7. 切换语言
8. 退出
""",
        "select_option": "请选择操作：",
        "enter_account": "请输入账户名：",
        "enter_password": "请输入密码（按回车生成随机密码）：",
        "account_exists": "账户已存在！",
        "password_saved": "密码保存成功！",
        "account_not_found": "未找到该账户！",
        "password_for": "{}的密码是：{}",
        "no_passwords": "没有存储的密码。",
        "accounts_list": "已存储的账户：",
        "delete_success": "密码删除成功！",
        "select_language": "选择语言 (en/zh)：",
        "invalid_option": "无效选项，请重试。",
        "goodbye": "再见！",
        "enter_password_length": "请输入密码长度：",
        "enter_exclude_chars": "请输入要排除的字符(可选)：",
        "enter_note": "请输入备注信息(可选)：",
        "enter_search_keyword": "请输入搜索关键词(可选)：",
        "enter_password_id": "请输入密码ID：",
        "enter_export_path": "请输入导出文件路径：",
        "enter_import_path": "请输入导入文件路径：",
        "language_changed": "语言已更改！",
        "press_enter": "按回车键继续...",
        "generated_password": "生成的密码：",
        "generation_time": "生成耗时：{}秒",
        "satisfied_password": "是否满意这个密码？",
        "modify_parameters": "是否要修改生成参数？",
        "enter_new_length": "请输入新的密码长度：",
        "regenerating": "正在重新生成密码...",
        "no_permission_dir": "没有权限创建目录：{}",
        "no_permission_file": "没有权限写入文件：{}",
        "invalid_path": "无效的文件路径：{}",
        "help_password_length": "密码长度",
        "help_exclude_chars": "要排除的字符",
        "help_account_name": "账号名称",
        "help_note": "备注信息",
        "help_search": "搜索关键词",
        "help_password_id": "要删除的密码ID",
        "help_export_path": "导出文件路径",
        "help_import_path": "导入文件路径",
        "seconds": "秒",
        "back_to_menu": "返回主菜单",
        "back_option": "输入'b'返回主菜单",
        "going_back": "正在返回主菜单...",
        "found_records": "找到 {} 条记录",
        "no_records_found": "未找到任何记录",
        "record_details": "记录详情",
        "warning_delete_all": "警告：即将删除所有 {} 条密码记录！",
        "existing_records": "现有记录",
        "operation_irreversible": "此操作不可恢复！",
        "confirm_clear_all": "是否确认清空所有记录？",
        "confirm_clear_all_again": "再次确认是否清空所有记录？",
        "clear_cancelled": "已取消清空操作",
        "no_records_in_db": "数据库中没有任何记录",
        "confirm_delete": "确认删除这条记录？",
        "delete_cancelled": "已取消删除操作",
        "file_not_exists": "文件不存在：{}",
        "export_success": "密码已成功导出到：{}",
        "export_failed": "导出失败：{}",
        "import_success": "已成功从 {} 导入密码",
        "import_failed": "导入失败：{}",
        "clear_success": "已成功清空所有记录",
        "clear_failed": "清空操作失败",
        "delete_success": "已成功删除记录",
        "delete_failed": "删除失败",
        "available_accounts": "可删除的账户列表：",
        "account_id_format": "ID：{}，账户：{}",
        "search_before_delete": "删除前搜索账户(可选)：",
        "more_records": "...还有 {} 条记录（使用搜索功能筛选）",
        "delete_options": """选择操作：
1. 直接输入ID删除
2. 搜索后删除""",
        "select_delete_option": "请选择操作：",
    }
} 